# Site settings
title: Christoph Dressler

navigation:
  - title: galleries
    url: index.html
  - title: clients
    url: article.html
  - title: info
    url: info.html

collections:
  galleries:
    output: true

# Build settings
markdown: kramdown
highlighter: pygments
safe: true
lsi: false

sass:
  style: compressed
