# Site settings
title: Christoph Dressler
description: >
  This site is an example for a simple Jekyll-powered portfolio website.
baseurl: "/squaregen"

# Build settings
markdown: kramdown
highlighter: pygments
safe: true
lsi: false
