# Site settings
title: Christoph Dressler
baseurl: "/squaregen"

navigation:
  - title: galleries
    url: /index.html
  - title: clients
    url: /article.html
  - title: info
    url: /info.html

# Build settings
markdown: kramdown
highlighter: pygments
safe: true
lsi: false

sass:
  style: compressed