# Site settings
title: SquareClone example page
email: cmail@cuveland.de
description: >
  This site is an example for a simple Jekyll-powered portfolio website.
baseurl: "/squaregen/"
url: "http://cuveland.de"

# Build settings
markdown: kramdown
highlighter: pygments
safe: true
lsi: false
