# Site settings
title: Christoph Dressler

navigation:
  - title: galleries
    url: index.html
  - title: clients
    url: http://example.com
  - title: info
    url: info.html

collections:
  galleries:
    output: true

defaults:
  - scope:
      path: ""
      type: galleries
    values:
      layout: gallery

# Build settings
markdown: kramdown
highlighter: pygments
safe: true
lsi: false

exclude: ["Gemfile", "Gemfile.lock"]

sass:
  style: compressed
